// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-6u9fniEmriIHR2fmX1bUKiHBrOGns7g',
    appId: '1:876120005023:web:bc1a2fb05a08c343ed85aa',
    messagingSenderId: '876120005023',
    projectId: 'campus-5d27e',
    authDomain: 'campus-5d27e.firebaseapp.com',
    storageBucket: 'campus-5d27e.appspot.com',
    measurementId: 'G-2SDH30CYRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHRCExNo7KIleEmvsx5dtmrPNIpguYFiE',
    appId: '1:876120005023:android:882633dae08bc947ed85aa',
    messagingSenderId: '876120005023',
    projectId: 'campus-5d27e',
    storageBucket: 'campus-5d27e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDV4LTnAxBUJ7t_cpDg6LLHjI0fEE0ltY',
    appId: '1:876120005023:ios:b9938e514290614fed85aa',
    messagingSenderId: '876120005023',
    projectId: 'campus-5d27e',
    storageBucket: 'campus-5d27e.appspot.com',
    iosBundleId: 'com.example.campusSecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDV4LTnAxBUJ7t_cpDg6LLHjI0fEE0ltY',
    appId: '1:876120005023:ios:b9938e514290614fed85aa',
    messagingSenderId: '876120005023',
    projectId: 'campus-5d27e',
    storageBucket: 'campus-5d27e.appspot.com',
    iosBundleId: 'com.example.campusSecure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-6u9fniEmriIHR2fmX1bUKiHBrOGns7g',
    appId: '1:876120005023:web:53f08a8ca2b89e38ed85aa',
    messagingSenderId: '876120005023',
    projectId: 'campus-5d27e',
    authDomain: 'campus-5d27e.firebaseapp.com',
    storageBucket: 'campus-5d27e.appspot.com',
    measurementId: 'G-NYNZ65BZMK',
  );

}